#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PACKAGE_DIR="$ROOT_DIR/mac/66TaskLight"

python3 -m unittest discover -s "$ROOT_DIR/cli/tests" -p 'test_*.py'
(cd "$ROOT_DIR" && "$ROOT_DIR/script/swift_test_verified.sh")
(cd "$PACKAGE_DIR" && swift build)
(cd "$PACKAGE_DIR" && swift run TaskLightChecks)
"$ROOT_DIR/script/smoke_ui_refresh_latency.sh"
"$ROOT_DIR/script/smoke_render_snapshot_coordinator.sh"
"$ROOT_DIR/script/smoke_signal_bus.sh"
"$ROOT_DIR/script/smoke_reliability_m38.sh"
"$ROOT_DIR/script/smoke_observability_m39.sh"
"$ROOT_DIR/script/smoke_expansion_m40.sh"
"$ROOT_DIR/script/smoke_state_projector.sh"
"$ROOT_DIR/script/smoke_state_projector_snapshot_cache.sh"
"$ROOT_DIR/script/smoke_codex_quota.sh"
"$ROOT_DIR/script/smoke_codex_quota_watcher.sh"
"$ROOT_DIR/script/smoke_quota_writer_ownership.sh"
"$ROOT_DIR/script/smoke_tasklight_runtime_stage.sh"
"$ROOT_DIR/script/smoke_codex_quota_reset_credits.sh"
"$ROOT_DIR/script/smoke_codex_quota_watcher_launch_agent.sh"
"$ROOT_DIR/script/smoke_widget_snapshot.sh"
"$ROOT_DIR/script/smoke_widgetkit_xcode_wrapper.sh"
"$ROOT_DIR/script/smoke_widgetkit_desktop_acceptance.sh"
"$ROOT_DIR/script/smoke_permission_safe_launch.sh"
"$ROOT_DIR/script/smoke_quota_burn_rate.sh"
"$ROOT_DIR/script/smoke_quota_burn_rate_maturity.sh"
"$ROOT_DIR/script/smoke_usage_provider_adapter.sh"
"$ROOT_DIR/script/smoke_operational_insights.sh"
"$ROOT_DIR/script/smoke_turn_runtime_arbiter.sh"
"$ROOT_DIR/script/smoke_multitask.sh"
"$ROOT_DIR/script/smoke_verify_gate.sh"
"$ROOT_DIR/script/smoke_ttl.sh"
"$ROOT_DIR/script/smoke_invalid_task_json.sh"
"$ROOT_DIR/script/smoke_observations.sh"
"$ROOT_DIR/script/smoke_current_thread_binding.sh"
"$ROOT_DIR/script/smoke_appserver_bridge.sh"
"$ROOT_DIR/script/smoke_appserver_thread_watcher.sh"
"$ROOT_DIR/script/smoke_codex_thread_coverage.sh"
"$ROOT_DIR/script/smoke_status_reflection_cases.sh"
"$ROOT_DIR/script/smoke_workspace_coverage.sh"
"$ROOT_DIR/script/smoke_workspace_hooks_doctor.sh"
"$ROOT_DIR/script/smoke_workspace_hooks_install_confirm.sh"
"$ROOT_DIR/script/smoke_hooks_config.sh"
"$ROOT_DIR/script/smoke_hook_signal_bridge.sh"
"$ROOT_DIR/script/smoke_hook_bridge_idle_cache.sh"
"$ROOT_DIR/script/smoke_check_all_total_schema.sh"
"$ROOT_DIR/script/smoke_stop_priority_guard.sh"
"$ROOT_DIR/script/smoke_hook_bridge_launch_agent.sh"
"$ROOT_DIR/script/smoke_signal_fusion.sh"
"$ROOT_DIR/script/smoke_private_probe_confidence.sh"
"$ROOT_DIR/script/smoke_current_thread_turn_identity.sh"
"$ROOT_DIR/script/smoke_observer_health.sh"
"$ROOT_DIR/script/smoke_self_review.sh"
"$ROOT_DIR/script/smoke_self_review_scope.sh"
"$ROOT_DIR/script/smoke_self_review_generate_scope.sh"
"$ROOT_DIR/script/smoke_luckycat_edge_toggle_atomic.sh"
"$ROOT_DIR/script/smoke_edge_glass_module_boundaries.sh"
"$ROOT_DIR/script/smoke_luckycat_edge_toggle_runtime.sh"
"$ROOT_DIR/script/smoke_status_orb_interaction_rules.sh"
"$ROOT_DIR/script/smoke_tasklight_interaction_event_replay.sh"
"$ROOT_DIR/script/check_component_audit_guardrails.sh"
"$ROOT_DIR/script/smoke_luckycat_expanded_panel.sh"
"$ROOT_DIR/script/smoke_luckycat_expanded_panel_runtime.sh"
"$ROOT_DIR/script/smoke_luckycat_menu_bar.sh"
"$ROOT_DIR/script/smoke_luckycat_menu_bar_runtime.sh"
"$ROOT_DIR/script/smoke_macos27_kit_glass_ui.sh"
"$ROOT_DIR/script/smoke_luckycat_visual_matrix.sh"
"$ROOT_DIR/script/smoke_luckycat_visual_matrix_readability.sh"
"$ROOT_DIR/script/smoke_luckycat_visual_matrix_runtime.sh"
"$ROOT_DIR/script/smoke_status_replay_history.sh"
"$ROOT_DIR/script/smoke_focus_meeting_mode.sh"
python3 "$ROOT_DIR/script/state_projector.py" --once >/dev/null
"$ROOT_DIR/script/check_state_projector.sh" >/dev/null
"$ROOT_DIR/script/build_and_run.sh" --verify
"$ROOT_DIR/script/check_ui_client.sh" >/dev/null
